import { mitsOfficialClubsSeed } from './mitsClubsSeed.js';

export const initialSeedData = {
  users: [
    {
      id: 'usr_admin_01',
      name: 'Dr. Arthur Vance (Dean)',
      email: 'admin@college.edu',
      role: 'ADMIN',
      department: 'Administration',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      isActive: true,
    },
    {
      id: 'usr_fac_01',
      name: 'Prof. Ramesh Sharma',
      email: 'faculty.sharma@college.edu',
      role: 'FACULTY',
      facultyId: 'FAC-CSE-104',
      department: 'Computer Science & Engineering',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      isActive: true,
    },
    {
      id: 'usr_fac_02',
      name: 'Dr. Meenakshi Sundaram',
      email: 'faculty.meenakshi@college.edu',
      role: 'FACULTY',
      facultyId: 'FAC-ECE-208',
      department: 'Electronics & Communication',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
      isActive: true,
    },
    {
      id: 'usr_stu_01',
      name: 'Rahul Verma',
      email: 'rahul.verma@college.edu',
      role: 'STUDENT',
      studentId: 'STU-2023-CS042',
      department: 'Computer Science',
      year: '3rd Year',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
      isActive: true,
    },
    {
      id: 'usr_stu_02',
      name: 'Hariom Gupta',
      email: 'hariom@college.edu',
      role: 'STUDENT',
      studentId: 'STU-2024-IT019',
      department: 'Information Technology',
      year: '2nd Year',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
      isActive: true,
    },
    {
      id: 'usr_stu_03',
      name: 'Priya Nair',
      email: 'priya.nair@college.edu',
      role: 'STUDENT',
      studentId: 'STU-2023-EC088',
      department: 'Electronics',
      year: '3rd Year',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
      isActive: true,
    },
  ],

  clubs: mitsOfficialClubsSeed,

  clubMembers: [
    {
      id: 'cm_01',
      clubId: 'club_12',
      userId: 'usr_stu_01',
      studentName: 'Rahul Verma',
      studentEmail: 'rahul.verma@college.edu',
      position: 'President',
      permissions: {
        canCreateEvents: true,
        canEditEvents: true,
        canDeleteEvents: true,
        canManageHiring: true,
        canManageMembers: true,
        canPostAchievements: true,
      },
      joiningDate: '2023-08-15',
      status: 'ACTIVE',
    },
    {
      id: 'cm_02',
      clubId: 'club_12',
      userId: 'usr_stu_02',
      studentName: 'Hariom Gupta',
      studentEmail: 'hariom@college.edu',
      position: 'Technical Member',
      permissions: {
        canCreateEvents: false,
        canEditEvents: false,
        canDeleteEvents: false,
        canManageHiring: false,
        canManageMembers: false,
        canPostAchievements: false,
      },
      joiningDate: '2024-01-10',
      status: 'ACTIVE',
    },
    {
      id: 'cm_03',
      clubId: 'club_06',
      userId: 'usr_stu_02',
      studentName: 'Hariom Gupta',
      studentEmail: 'hariom@college.edu',
      position: 'Student Member',
      permissions: {
        canCreateEvents: false,
        canEditEvents: false,
        canDeleteEvents: false,
        canManageHiring: false,
        canManageMembers: false,
        canPostAchievements: false,
      },
      joiningDate: '2024-02-01',
      status: 'ACTIVE',
    },
    {
      id: 'cm_04',
      clubId: 'club_12',
      userId: 'usr_stu_03',
      studentName: 'Priya Nair',
      studentEmail: 'priya.nair@college.edu',
      position: 'Technical Head',
      permissions: {
        canCreateEvents: true,
        canEditEvents: true,
        canDeleteEvents: false,
        canManageHiring: true,
        canManageMembers: false,
        canPostAchievements: true,
      },
      joiningDate: '2023-09-01',
      status: 'ACTIVE',
    },
  ],

  achievements: [
    {
      id: 'ach_col_deemed_univ',
      title: 'Deemed-to-be University',
      description:
        'Declared a Deemed-to-be University under Distinct Category by the Ministry of Education, Government of India in 2024.',
      image: '/mits-campus.jpg',
      category: 'COLLEGE',
      department: 'MITS Gwalior',
      date: '2024-06-15',
      isApproved: true,
    },
    {
      id: 'ach_col_naac_app',
      title: 'NAAC A++ Accreditation',
      description:
        'MITS has received the NAAC A++ grade, with a CGPA of 3.53.',
      image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80',
      category: 'COLLEGE',
      department: 'MITS Gwalior',
      date: '2023-11-20',
      isApproved: true,
    },
    {
      id: 'ach_col_nba_programs',
      title: 'NBA Accredited Programs',
      description:
        'Several MITS academic programmes are accredited by the National Board of Accreditation (NBA).\nFor example, the Civil Engineering B.Tech programme received NBA accreditation for 6 years from July 2021.',
      image: '/campus-bg.jpg',
      category: 'COLLEGE',
      department: 'MITS Gwalior',
      date: '2021-07-01',
      isApproved: true,
    },
    {
      id: 'ach_col_01',
      title: 'NIRF Ranking #14 in Engineering Excellence',
      description:
        'The college was awarded national distinction for top placement rates, research citations, and state-of-the-art incubation laboratories.',
      image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80',
      category: 'COLLEGE',
      department: 'MITS Gwalior',
      date: '2026-08-10',
      isApproved: true,
    },
    {
      id: 'ach_stu_01',
      title: 'First Prize at National AI Innovations Summit',
      description:
        'Final year team designed an edge-AI vision system for assistive medical diagnostics, beating 280 national university teams.',
      image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
      category: 'STUDENT',
      studentName: 'Priya Nair & Team',
      department: 'Electronics & CS',
      year: '3rd & 4th Year',
      date: '2026-08-28',
      isApproved: true,
    },
    {
      id: 'ach_club_01',
      title: 'Competitive Coding Club Wins Grand Trophy at HackCon 2026',
      description:
        'Coding Club sent 4 squads to the 36-hour Inter-College Hackathon and secured 1st overall trophy with $10,000 in sponsor grants.',
      image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop&q=80',
      category: 'CLUB',
      clubName: 'Competitive Coding Club',
      date: '2026-09-02',
      isApproved: true,
    },
  ],

  events: [
    {
      id: 'evt_01',
      title: 'HackGenesis 2026: 24-Hour Annual Hackathon',
      clubId: 'club_12',
      clubName: 'Competitive Coding Club',
      description:
        'Build cutting-edge full-stack, AI, and Web3 applications. Mentorship sessions by tech leaders from Google and Microsoft, free swag, food, and $5,000 prize pool.',
      poster: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
      date: '2026-09-26',
      time: '09:00 AM - 09:00 AM (Next Day)',
      venue: 'Main Auditorium & CS Labs 1-4',
      registrationLink: 'https://forms.google.com/cms-hackgenesis-2026',
      category: 'Technical',
      tags: ['Hackathon', 'WebDev', 'AI', 'Prizes'],
      isPublished: true,
    },
    {
      id: 'evt_02',
      title: 'Autonomous Drone Flight & ROS Workshop',
      clubId: 'club_06',
      clubName: 'ASIMOV (Robotics Club)',
      description:
        'Interactive hands-on session on assembling quadcopters, writing flight controllers using PX4, and simulating obstacle avoidance with ROS2.',
      poster: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
      date: '2026-10-03',
      time: '02:00 PM - 05:30 PM',
      venue: 'Robotics Center Lab B',
      registrationLink: 'https://forms.google.com/cms-drone-ros-2026',
      category: 'Workshop',
      tags: ['Robotics', 'ROS2', 'Hardware', 'Drones'],
      isPublished: true,
    },
    {
      id: 'evt_03',
      title: 'Acoustic Fest & Battle of the Bands',
      clubId: 'club_07',
      clubName: 'Bandish: Music Club of MITS',
      description:
        'An open-air musical evening featuring live indie bands, campus acoustic acts, beatboxers, and culinary street stalls under the stars.',
      poster: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=80',
      date: '2026-10-12',
      time: '06:00 PM - 10:00 PM',
      venue: 'College Open Air Amphitheatre',
      registrationLink: 'https://forms.google.com/cms-acoustic-night',
      category: 'Cultural',
      tags: ['Music', 'Live Performance', 'Fest', 'OpenAir'],
      isPublished: true,
    },
    {
      id: 'evt_04',
      title: 'Inter-College Invitational Cricket Cup',
      clubId: 'club_60',
      clubName: 'Sports Club',
      description:
        'Cheer for the college varsity team as 16 regional universities compete for the prestigious Chancellor Golden Trophy.',
      poster: 'https://images.unsplash.com/photo-1531415074868-036b1c57e329?w=800&auto=format&fit=crop&q=80',
      date: '2026-10-18',
      time: '08:30 AM - 05:00 PM',
      venue: 'Main College Sports Complex Grounds',
      registrationLink: 'https://forms.google.com/cms-cricket-varsity',
      category: 'Sports',
      tags: ['Cricket', 'Varsity', 'Championship'],
      isPublished: true,
    },
  ],

  hiring: [
    {
      id: 'hire_01',
      clubId: 'club_12',
      clubName: 'Competitive Coding Club',
      position: 'Full-Stack Developer & Technical Lead',
      description:
        'Looking for passionate 2nd/3rd year developers proficient in React, Node.js, and TypeScript to architect next-gen student portals and manage internal club repositories.',
      eligibility: 'B.Tech/BE Students (2nd & 3rd Year, Any Branch)',
      requiredSkills: ['React', 'Node.js', 'Git', 'REST APIs'],
      deadline: '2026-09-30',
      poster: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop&q=80',
      applicationLink: 'https://forms.google.com/cms-coding-club-hiring',
      status: 'OPEN',
    },
    {
      id: 'hire_02',
      clubId: 'club_06',
      clubName: 'ASIMOV (Robotics Club)',
      position: 'Embedded Systems & Firmware Engineer',
      description:
        'Join the core hardware team to design custom PCBs, program STM32 microcontrollers, and prepare teams for international rovers competitions.',
      eligibility: 'Open to 1st, 2nd, and 3rd year engineering students',
      requiredSkills: ['C/C++', 'Arduino/STM32', 'Circuit Design', 'Soldering'],
      deadline: '2026-10-05',
      poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
      applicationLink: 'https://forms.google.com/cms-robotics-hiring',
      status: 'OPEN',
    },
  ],

  facultyPosts: [
    {
      id: 'fpost_hack_01',
      title: 'HackMITS 2026: 36-Hour National Student Hackathon Call for Submissions',
      content:
        'We invite student innovators across all departments to register for HackMITS 2026! Tracks include Generative AI, Sustainable IoT, Robotics & Autonomous Systems, and Fintech. Teams of 3-5 students can submit proposals. Faculty mentorship sessions provided throughout the 36-hour sprint.',
      category: 'Hackathon',
      postType: 'HACKATHON',
      link: 'https://hackmits.mits.edu/register',
      prizePool: '₹2,50,000 + Paid Summer Research Fellowships',
      facultyId: 'usr_fac_01',
      facultyName: 'Prof. Ramesh Sharma',
      department: 'Computer Science & Engineering',
      image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
      likesCount: 68,
      commentsCount: 12,
      isPinned: true,
      createdAt: '2026-09-10T09:30:00.000Z',
    },
    {
      id: 'fpost_link_01',
      title: 'Resource Link: Access IEEE Xplore & ACM Digital Library via MITS Proxy',
      content:
        'Students and research scholars can now access full-text PDF papers, journals, and conference proceedings through the institutional proxy login. Click the website link to authenticate with your college credentials.',
      category: 'Website Link',
      postType: 'LINK',
      link: 'https://ieeexplore.ieee.org',
      facultyId: 'usr_fac_01',
      facultyName: 'Prof. Ramesh Sharma',
      department: 'Computer Science & Engineering',
      image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&auto=format&fit=crop&q=80',
      likesCount: 35,
      commentsCount: 4,
      isPinned: false,
      createdAt: '2026-09-09T14:15:00.000Z',
    },
    {
      id: 'fpost_01',
      title: 'Announcement: Guidelines for Mid-Semester Capstone Project Reviews',
      content:
        'All 3rd and 4th year project teams must submit their Phase 1 design documents and Git repository links by next Friday 5 PM. Plagiarism checks will be enforced.',
      category: 'Academic Notice',
      postType: 'NOTICE',
      facultyId: 'usr_fac_01',
      facultyName: 'Prof. Ramesh Sharma',
      department: 'Computer Science & Engineering',
      image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80',
      likesCount: 24,
      commentsCount: 3,
      isPinned: true,
      createdAt: '2026-09-08T10:00:00.000Z',
    },
    {
      id: 'fpost_02',
      title: 'Guest Lecture by Google DeepMind Principal Research Scientist',
      content:
        'We are delighted to announce Dr. S. Ramanujan delivering an exclusive session on "Multimodal Foundation Models and Efficient Inference on Edge Devices" on Thursday at 3 PM in Seminar Hall 2.',
      category: 'Research & Guest Lectures',
      postType: 'NOTICE',
      facultyId: 'usr_fac_02',
      facultyName: 'Dr. Meenakshi Sundaram',
      department: 'Electronics & Communication',
      image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop&q=80',
      likesCount: 47,
      commentsCount: 5,
      isPinned: false,
      createdAt: '2026-09-07T14:30:00.000Z',
    },
  ],

  comments: [
    {
      id: 'cmt_01',
      postId: 'fpost_01',
      userId: 'usr_stu_01',
      userName: 'Rahul Verma',
      userRole: 'STUDENT',
      content: 'Thank you Professor! Will there be a rubric template shared for the slide presentation format?',
      createdAt: '2026-09-08T11:15:00.000Z',
    },
    {
      id: 'cmt_02',
      postId: 'fpost_01',
      userId: 'usr_fac_01',
      userName: 'Prof. Ramesh Sharma',
      userRole: 'FACULTY',
      content: 'Yes Rahul, the departmental review rubric has been uploaded to the CMS course portal.',
      createdAt: '2026-09-08T11:45:00.000Z',
    },
  ],

  notifications: [
    {
      id: 'notif_01',
      title: 'HackGenesis 2026 Registration Open',
      message: 'Coding Club announced HackGenesis 2026. Register your squad before spots fill up!',
      type: 'NEW_EVENT',
      link: '/events',
      createdAt: '2026-09-09T08:00:00.000Z',
      isRead: false,
    },
    {
      id: 'notif_02',
      title: 'New Opportunity: Coding Club Hiring Lead',
      message: 'Coding Club is recruiting Full-Stack and Tech Leads. Applications close Sept 30.',
      type: 'NEW_HIRING',
      link: '/opportunities',
      createdAt: '2026-09-08T16:00:00.000Z',
      isRead: false,
    },
  ],
};
